apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: board-games-backendconfig
spec:
  timeoutSec: 50
  connectionDraining:
    drainingTimeoutSec: 60
  sessionAffinity:
    affinityType: "GENERATED_COOKIE"
    affinityCookieTtlSec: 3600
