version: '3.4'
services:
  db:
    image: "docker.io/bitnami/postgresql:13"
    environment:
      POSTGRES_PASSWORD: "Fusion.0.to.1"
    expose:
     - "5432"
    ports:
     - "5432:5432"

  app_debug:
    build:
      context: .
      target: app_debug
    depends_on:
     - db
    ports:
      - "5030:5030"
    environment:
      ASPNETCORE_URLS: "http://*:5030"
      BoardGames__UsePostgreSql: "Server=db;Database=board_games_dev;Port=5432;User Id=postgres;Password=Fusion.0.to.1"

  app_release:
    build:
      context: .
      target: app_release
    depends_on:
     - db
    ports:
     - "80:80"
    environment:
      ASPNETCORE_URLS: "http://*:80"
      HTTPS_PORT: 443
      BoardGames__UsePostgreSql: "Server=db;Database=board_games_dev;Port=5432;User Id=postgres;Password=Fusion.0.to.1"
