apiVersion: v1
kind: Service
metadata:
  name: board-games-service
spec:
  type: NodePort
  selector:
    app: board-games
  ports:
    - port: 10000
      targetPort: 80
      protocol: TCP
      name: http
  externalTrafficPolicy: Local
