apiVersion: v1
kind: Service
metadata:
  name: board-games-service
spec:
  type: ClusterIP
  selector:
    app: board-games
  ports:
    - port: 80
      targetPort: 80
  externalTrafficPolicy: Local
